fix: set pixel to 255
Traceback (most recent call last):
  File "/data/hdd1/by/House-Prices-Advanced-Regression-Techniques/train.py", line 991, in <module>
    train(net, train_loader, val_loader, writer, args)
  File "/data/hdd1/by/House-Prices-Advanced-Regression-Techniques/train.py", line 127, in train
    for iter_idx, (images, masks, weight_maps) in enumerate(train_iterloader):
  File "/data/hdd1/by/House-Prices-Advanced-Regression-Techniques/dataloader/iterloader.py", line 12, in __next__
    data = next(self.iter_loader)
  File "/home/baiyu/miniconda3/envs/torch1.13/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/baiyu/miniconda3/envs/torch1.13/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/home/baiyu/miniconda3/envs/torch1.13/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/baiyu/miniconda3/envs/torch1.13/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/baiyu/miniconda3/envs/torch1.13/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/baiyu/miniconda3/envs/torch1.13/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/baiyu/miniconda3/envs/torch1.13/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/hdd1/by/House-Prices-Advanced-Regression-Techniques/dataset/glas.py", line 136, in __getitem__
    image, label, weight_map = self.transforms(image, label, weight_map)
  File "/data/hdd1/by/House-Prices-Advanced-Regression-Techniques/transforms.py", line 47, in __call__
    img, mask, weight_map = trans(img, mask, weight_map)
  File "/data/hdd1/by/House-Prices-Advanced-Regression-Techniques/transforms.py", line 470, in __call__
    raise ValueError('still no pixels of class???')
ValueError: still no pixels of class???